version: 0.0.1

services:
  db:
    container_name: NekoGPT_DB
    image: mariadb:latest
    environment:
      - MARIADB_USER=NekoGPT
      - MARIADB_PASSWORD=xO6_s*xJtd
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=NekoGPT
    ports:
      - 3306:3306

  app:
    container_name: NekoGPT
    image: cocomine/nekogpt:latest
    environment:
      - BOT_NAME=NekoGPT
      - CHATGPT_TOKEN=(Your ChatGPT access token)
      - DISCORD_TOKEN=(Your Discord token)
      - MYSQL_DATABASE=NekoGPT
      - MYSQL_HOST=NekoGPT_DB
      - MYSQL_USER=NekoGPT
      - MYSQL_PASSWORD=xO6_s*xJtd
    links:
      - db
    depends_on:
      - db